def generate_report(bruteforce, suspicious_ips, privilege_events, risk_score, risk_level):
    report = []

    report.append("=" * 60)
    report.append("                    LOGSENTRY INCIDENT REPORT")
    report.append("=" * 60 + "\n")

    # Summary
    report.append("Summary")
    report.append("-" * 7)
    report.append(f"Risk Level        : {risk_level}")
    report.append(f"Total Risk Score  : {risk_score}\n")

    # Detected threats summary
    high_bf = len(bruteforce.get("high", []))
    low_bf = len(bruteforce.get("low", []))

    report.append("Detected Threats")
    report.append("-" * 16)
    report.append(f"Brute-Force Attacks (High) : {high_bf} IP(s)")
    report.append(f"Low & Slow Attempts       : {low_bf} IP(s)")

    # Highlight multiple low-and-slow IPs
    if low_bf >= 2:
        report.append("    ⚠ Multiple Low & Slow IPs detected (potential distributed attack)")

    report.append(f"Suspicious IP Activity    : {len(suspicious_ips)} IP(s)")
    report.append(f"Privilege Escalation      : {len(privilege_events)} event(s)\n")

    # Detailed findings
    report.append("Detailed Findings")
    report.append("-" * 17 + "\n")

    if high_bf > 0 or low_bf > 0:
        report.append("[1] Brute-Force Login Attempts")
        for ip in bruteforce.get("high", []):
            report.append(f"    - HIGH severity IP : {ip}")
        for ip in bruteforce.get("low", []):
            report.append(f"    - LOW & SLOW IP    : {ip}")
        report.append("")

    if suspicious_ips:
        report.append("[2] Suspicious IP Addresses")
        for ip in suspicious_ips:
            report.append(f"    - {ip}")
        report.append("")

    if privilege_events:
        report.append("[3] Privilege Escalation Attempts")
        for event in privilege_events:
            report.append(f"    - {event}")
        report.append("")

    # Recommendations
    report.append("Recommendations")
    report.append("-" * 15)
    report.append("✔ Block or firewall offending IP addresses")
    report.append("✔ Review and restrict sudo permissions")
    report.append("✔ Enable SSH key-based authentication")
    report.append("✔ Monitor authentication logs continuously\n")

    report.append("Report Generated By : LogSentry")
    report.append("=" * 60)

    return "\n".join(report)
